### ISSUE TITLE
To do

### ISSUE THREAD

**Issue by renatosbispo** [renatosbispo/blaze-crash-simulator#2]
- [x] **Planning**
  - [x] [Define the program flow](https://github.com/renatosbispo/blaze-crash-simulator/issues/3)
  - [x] Define the project tasks
  - [x] [Define the data structures](https://github.com/renatosbispo/blaze-crash-simulator/issues/4)
  - [x] [Define the program data directory structure](https://github.com/renatosbispo/blaze-crash-simulator/issues/5)
  - [x] Decide whether the program data should be loaded entirely at once or individually where needed
  
---

- [ ] **Main program flow**
  - [x] Setup program data directory
  - [x] Initiate sample collection
  - [x] Save sample
  - [ ] Ask for strategy
  - [ ] Initiate strategy simulation
  - [ ] Save strategy
  - [ ] Show all strategies with respective simulation results
  - [ ] Add option to add new strategy
  - [ ] Add option to exit by pressing `<Esc>`

---
  
- [x] **Crash points sample collection**
  - [x] Setup automated browser
  - [x] Collect sample data
  - [x] Build sample structure
  
---
  
- [ ] **Betting strategy simulation**
  - [ ] Load sample
  - [ ] Execute strategy on sample
  - [ ] Add simulation results to strategy

---

- [x] **Refactoring**
  - [x] Create internal lib for dealing with console output

---

- [ ] **Improvements**
  - [ ] Simulate existing strategies after new sample collection
